[package]
name = "game_of_life_rust"
version = "0.1.0"
authors = ["Trystan Hendricks <dolkhound@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
crossterm = "0.20.0"